#!/usr/bin/env python3
"""Generates Haxe raw bindings and the HashLink HDLL shim from lib/rnl.h.

Usage:  python3 tools/gen_raw.py [path/to/rnl.h]

Outputs (relative to hx_rnl/):
  source/rnl/raw/Raw.hx           facade: externs for cpp/hl, stubs otherwise
  source/rnl/raw/RawUnavailable.hx
  project/hdll/rnl_hdll.c         HL_PRIM shim compiled into rnl.hdll

Conventions:
  * int64 parameters are split into two int32 halves (_lo/_hi) on the HashLink
    backend; the facade keeps a single haxe.Int64 parameter.
  * int64 return values are likewise exposed as _lo()/_hi() pairs on hl and
    reassembled into Int64 by the facade.
"""
import re, sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
HDR = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, '..', 'lib', 'rnl.h')

src = open(HDR).read()

# ---------------------------------------------------------------- parse ----
pat = re.compile(
    r'RNL_API\s+([A-Za-z_0-9 ]+?\*?)\s*\b(RNL_[a-z0-9_]+)\s*\((.*?)\)\s*;', re.S)
entries = []
for ret, name, args in pat.findall(src):
    args = re.sub(r'\s+', ' ', args).strip()
    entries.append((ret.strip(), name, args))
assert len(entries) == 458, f'expected 458 exports, got {len(entries)}'

I64 = ('uint64_t', 'int64_t')

def split_params(args):
    """[(modifier, ctype, pname)] for a C argument list."""
    if not args or args == 'void':
        return []
    out, depth, cur = [], 0, ''
    for ch in args:
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        if ch == ',' and depth == 0:
            out.append(cur.strip()); cur = ''
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    res = []
    for p in out:
        pn = re.sub(r'\*\s*', '* ', p).strip()
        m = re.match(r'^(?:(const|out|var)\s+)?(.+?)\s+([A-Za-z_][A-Za-z0-9_]*)$', pn)
        if m:
            res.append((m.group(1) or '', m.group(2).strip(), m.group(3)))
        else:
            res.append(('', p.strip(), 'arg%d' % len(res)))
    return res

def is_i64(t):
    return t.strip() in I64

def hl_split_args(args):
    """[(final_cname, ctype)] with i64 params expanded to lo/hi pairs."""
    out = []
    for mod, typ, nm in split_params(args):
        t = typ.replace('const ', '')
        if is_i64(t):
            out.append((nm + '_lo', 'int32_t'))
            out.append((nm + '_hi', 'int32_t'))
        else:
            out.append((nm, typ))
    return out

def cpp_hx_type(t):
    t = t.replace('const ', '').strip()
    if t.endswith('*'):
        base = t[:-1].strip()
        if base == 'char':
            return 'CharPtr'
        return 'Ptr'
    return {'void': 'Void', 'bool': 'Bool', 'single': 'Float', 'double': 'Float',
            'int8_t': 'Int', 'uint8_t': 'Int', 'int16_t': 'Int',
            'uint16_t': 'Int', 'int32_t': 'Int', 'uint32_t': 'Int',
            'size_t': 'Int', 'ptrdiff_t': 'Int', 'char': 'Int',
            'uint64_t': 'Int64', 'int64_t': 'Int64'}.get(t, 'Ptr')

def hl_hx_type(t):
    t = t.replace('const ', '').strip()
    if t.endswith('*'):
        return 'hl.Bytes'
    return {'void': 'Void', 'bool': 'Bool', 'single': 'Float', 'double': 'Float',
            'int8_t': 'Int', 'uint8_t': 'Int', 'int16_t': 'Int',
            'uint16_t': 'Int', 'int32_t': 'Int', 'uint32_t': 'Int',
            'size_t': 'Int', 'ptrdiff_t': 'Int', 'char': 'Int'}.get(t, 'hl.Bytes')

# --------------------------------------------------------------- Raw.hx ----
L = []
A = L.append
A('package rnl.raw;')
A('')
A('import haxe.Int64;')
A('import rnl.raw.Types.Ptr;')
A('import rnl.raw.Types.CharPtr;')
A('')
A('/** Raw 1:1 bindings over the native library.')
A(' *  Generated by tools/gen_raw.py from lib/rnl.h - do not edit by hand.')
A(' *')
A(' *  int64 values travel as haxe.Int64 on every backend; the HashLink prim')
A(' *  layer splits them into _lo/_hi halves internally. */')

# --- #if hl section ---
A('#if hl')
A('@:keep')
A('@:hlNative("rnl")')
A('extern class _HlPrim {')
A('\tstatic function i64_to_ptr(lo:Int, hi:Int):Ptr;')
for ret, name, args in entries:
    ps = ', '.join('%s:%s' % (n, hl_hx_type(t)) for n, t in hl_split_args(args))
    if is_i64(ret):
        A('\tstatic function %s_lo(%s):Int;' % (name, ps))
        A('\tstatic function %s_hi(%s):Int;' % (name, ps))
    else:
        A('\tstatic function %s(%s):%s;' % (name, ps, hl_hx_type(ret)))
A('}')
A('')
A('@:keep')
A('class Raw {')
A('\tinline static function _low(v:Int64):Int return Int64.getLow(v);')
A('\tinline static function _high(v:Int64):Int return Int64.getHigh(v);')
A('\tinline static function _mk(lo:Int, hi:Int):Int64 return Int64.make(hi, lo);')
for ret, name, args in entries:
    if name == 'RNL_protocol_version':
        A('\tpublic static function %s():Int64 {' % name)
        A('\t\treturn _mk(_HlPrim.%s_lo(), _HlPrim.%s_hi());' % (name, name))
        A('\t}')
        continue
    params = []
    final = []
    for mod, typ, nm in split_params(args):
        if is_i64(typ):
            params.append('%s:Int64' % nm)
            final.append('_low(%s), _high(%s)' % (nm, nm))
        else:
            params.append('%s:%s' % (nm, hl_hx_type(typ)))
            final.append(nm)
    fa = ', '.join(final)
    if is_i64(ret):
        A('\tpublic static function %s(%s):Int64 {' % (name, ', '.join(params)))
        A('\t\treturn _mk(_HlPrim.%s_hi(%s), _HlPrim.%s_lo(%s));' % (name, fa, name, fa))
        A('\t}')
    else:
        hret = hl_hx_type(ret)
        A('\tpublic static function %s(%s):%s {' % (name, ', '.join(params), hret))
        call = '_HlPrim.%s(%s);' % (name, fa)
        A('\t\t%s%s' % ('' if hret == 'Void' else 'return ', call))
        A('\t}')
A('}')

# --- cpp section: externs with @:native, linked via BuildXml ---
A('#elseif (cpp && !(mac || ios))')
A('@:keep')
A('extern class Raw {')
for ret,name,args in entries:
    params=[];argc=0
    for mod,typ,nm in split_params(args):
        t=cpp_hx_type(typ)
        if is_i64(typ):
            if t=='Int64':
                params.append('%s:Int64'%nm);argc+=1
            else:
                params.append('%s:Int'%nm);argc+=1
        elif t=='Void':
            continue
        else:
            params.append('%s:%s'%(nm,t));argc+=1
    fa=', '.join(params)
    cret=cpp_hx_type(ret)
    A('\t@:native("%s")'%name)
    A('\tstatic function %s(%s):%s;'%(name,fa,cret))
A('}')

# --- stub section ---
A('#else')
A('@:keep')
A('class Raw {')
for ret, name, args in entries:
    params = []
    for mod, typ, nm in split_params(args):
        t = cpp_hx_type(typ)
        params.append('%s:%s' % (nm, t))
    cret = cpp_hx_type(ret)
    A('\tpublic static function %s(%s):%s {' % (name, ', '.join(params), cret))
    A('\t\tthrow new RawUnavailable("%s");' % name)
    A('\t}')
A('}')
A('#end')

open(os.path.join(ROOT, 'source/rnl/raw/Raw.hx'), 'w').write('\n'.join(L) + '\n')
print('Raw.hx:', len(entries), 'functions')

# -------------------------------------------------------- RawUnavailable ---
stub_err = '''package rnl.raw;

/** Thrown by the stub backend on platforms without shipped binaries yet
 *  (macOS / iOS). code mirrors RNL_ERR_UNSUPPORTED. */
class RawUnavailable extends haxe.Exception {
	public final code:Int;
	public function new(what:String, ?p:haxe.PosInfos) {
		super('RNL native library is not available on this platform yet (' + what + ')', p);
		code = -6;
	}
}
'''
open(os.path.join(ROOT, 'source/rnl/raw/RawUnavailable.hx'), 'w').write(stub_err)
print('RawUnavailable.hx written')



# ------------------------------------------------------------ rnl_hdll.c ---

def c_decl(name, args, ret):
    ra = re.sub(r'\s+', ' ', args).strip()
    if not ra or ra == 'void':
        return '%s %s(void)' % (ret, name)
    return '%s %s(%s)' % (ret, name, ra)

def hl_c_param_type(ct):
    """C type for an HDLL shim parameter."""
    t = ct.replace('const ', '').strip()
    if t.endswith('*'):
        return 'void*'
    return {'void':'void','bool':'int','single':'float','double':'double',
            'int8_t':'int','uint8_t':'int','uint16_t':'int','uint16_t':'int',
            'int32_t':'int','uint32_t':'unsigned int','size_t':'unsigned long',
            'ptrdiff_t':'int','char':'int'}.get(t, 'void*')

def c_ret_type(ret):
    t = ret.replace('const ', '').strip()
    if t == 'uint64_t' or t == 'int64_t':
        return t
    if t.endswith('*'):
        return t
    return {'void':'void','bool':'int','single':'float','double':'double',
            'uint8_t':'int','int8_t':'int','uint16_t':'int','int16_t':'int',
            'uint32_t':'unsigned int','size_t':'int','ptrdiff_t':'int',
            'char':'int'}.get(t, 'int')

def hl_fun_str(t):
    """_FUN type-string token for return."""
    t = t.replace('const ','').strip()
    if t.endswith('*'): return '_BYTES'
    return {'void':'_VOID','bool':'_BOOL','single':'_F32','double':'_F64',
            'int8_t':'_I32','uint8_t':'_I32','int16_t':'_I32','uint16_t':'_I32',
            'int32_t':'_I32','uint32_t':'_I32','size_t':'_I32',
            'ptrdiff_t':'_I32','char':'_I32',
            'uint64_t':'_I64','int64_t':'_I64'}.get(t,'_BYTES')

def hl_arg_strs(args):
    """List of _FUN arg-type-string tokens per parameter (i64-aware)."""
    out=[]
    for hn,ct in hl_split_args(args):
        t=ct.replace('const ','').strip()
        if t.endswith('*'): out.append('_BYTES')
        else:
            out.append({'void':'_VOID','bool':'_BOOL','single':'_F32',
                        'double':'_F64','int8_t':'_I32','uint8_t':'_I32',
                        'int16_t':'_I32','uint16_t':'_I32','int32_t':'_I32',
                        'uint32_t':'_I32','size_t':'_I32','ptrdiff_t':'_I32',
                        'char':'_I32','uint64_t':'_I64','int64_t':'_I64'
                       }.get(t,'_BYTES'))
    return out

def hl_transform(name):
	"""Haxe/HL compiler lowercases @:hlNative names and prepends underscore."""
	return '_' + name.lower()

def c_call_args(args):
    final=[]
    for mod,typ,nm in split_params(args):
        t=typ.replace('const ','').strip()
        if is_i64(t):
            final.append('((uint64_t)(uint32_t)%s_hi << 32 | (uint32_t)%s_lo)'%(nm,nm))
        elif t.startswith('struct ') and not t.endswith('*'):
            final.append('*('+t+'*)'+nm)
        else:
            final.append(nm)
    return ', '.join(final)

C=[]
C.append('/* rnl.hdll - HashLink shim over the RNL dynamic library.')
C.append(' * Generated by tools/gen_raw.py from lib/rnl.h - do not edit by hand.')
C.append(' */')
C.append('#define HL_NAME(x) rnl_##x')
C.append('#include <hl.h>')
C.append('')
C.append('#include <stdint.h>')
C.append('')
C.append('/* The real API, verbatim from the header. */')
C.append('#include "rnl.h"')
C.append('')
C.append('/* --- Int64 <-> pointer conversion helpers --- */')
C.append('HL_PRIM vbyte* HL_NAME(i64_to_ptr)(int32_t lo, int32_t hi) {')
C.append('\tuintptr_t v = ((uintptr_t)(uint32_t)hi << 32) | (uint32_t)lo;')
C.append('\treturn (vbyte*)(void*)(uintptr_t)v;')
C.append('}')
C.append('DEFINE_PRIM(_BYTES, i64_to_ptr, _I32 _I32);')
C.append('')

_seen=set()
for _ret,_name,_args in entries:
    if _name in _seen: continue
    _seen.add(_name)
    ra=re.sub(r'\s+',' ',_args).strip()
    if not ra or ra=='void':
        C.append('%s %s(void);'%(_ret,_name))
    else:
        C.append('%s %s(%s);'%(_ret,_name,ra))
C.append('')

for ret,name,args in entries:
    if name=='RNL_protocol_version':
        C.append('HL_PRIM int32_t HL_NAME(%s)(void) {'%hl_transform(name+'_lo'))
        C.append('\treturn (int32_t)(uint32_t)(%s() & 0xffffffffu);'%(name))
        C.append('}')
        C.append('DEFINE_PRIM(_I32,%s,_NO_ARG);'%hl_transform(name+'_lo'))
        C.append('HL_PRIM int32_t HL_NAME(%s)(void) {'%hl_transform(name+'_hi'))
        C.append('\treturn (int32_t)(uint32_t)(%s() >> 32);'%(name))
        C.append('}')
        C.append('DEFINE_PRIM(_I32,%s,_NO_ARG);'%hl_transform(name+'_hi'))
        continue

    ps=', '.join('%s %s'%(hl_c_param_type(ct),hn) for hn,ct in hl_split_args(args))
    cret=c_ret_type(ret)
    tname=hl_transform(name)
    callargs=c_call_args(args)
    arg_toks=' '.join(hl_arg_strs(args)) if hl_arg_strs(args) else '_NO_ARG'

    if cret in I64:
        # Two prims (_lo and _hi) for 64-bit return values
        for suffix, shift in [('_lo',''),('_hi',' >> 32')]:
            fname='HL_NAME(%s%s)'%(tname,suffix)
            C.append(('int32_t %s(%s)'%(fname,ps)) + ' {')
            C.append('\tuint64_t v = (uint64_t)%s(%s);'%(name,callargs))
            C.append('\treturn (int32_t)(uint32_t)((v%s) & 0xffffffffu);'%shift)
            C.append('}')
            C.append('DEFINE_PRIM(_I32,%s%s,%s);'%(tname,suffix,arg_toks))
    else:
        fname='HL_NAME(%s)'%tname
        header=('void %s(%s)'%(fname,ps)) if cret=='void' else ('%s %s(%s)'%(cret,fname,ps))
        C.append(header+' {')
        C.append('\treturn %s(%s);'%(name,callargs))
        C.append('}')
        prim_ret=hl_fun_str(ret)
        C.append('DEFINE_PRIM(%s,%s,%s);'%(prim_ret,tname,arg_toks))
    C.append('')

open(os.path.join(ROOT,'project/hdll/rnl_hdll.c'),'w').write('\n'.join(C)+'\n')
print('rnl_hdll.c:', sum(1 for l in C if l.startswith('DEFINE_PRIM')), 'prims')
